// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifdywigmxgwqdxobusql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZHl3aWdteGd3cWR4b2J1c3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzMwNjIsImV4cCI6MjA3MDEwOTA2Mn0.jOD2tTKhhzz_hMTJOOcL0se-dD2YIJckj9bcUg91FFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});