name: App-Store: Nightly Integrity Verify
on:
  schedule: [{ cron: "0 3 * * *" }]
permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app-store
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: npm ci || npm install
      - name: Schema check
        run: npx ajv validate -s schemas/registry.schema.json -d registry/index.json
      - name: Link existence check
        run: node scripts/verify-links.mjs